microlly/accounts/urls.py
from django.urls import path
from accounts import views

app_name='accounts'
urlpatterns=[
    path('signup/', views.signup_view, name='signup'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
]

microlly/microlly/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('microlly_blog.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

microlly/microlly_blog/urls.py
from django.urls import path
from microlly_blog import views

app_name = 'microlly_blog'
urlpatterns = [
    path('', views.index, name ='index'),
    path('create/', views.post_create, name='create'),
    path('post_user/<str:author>', views.list_post_user, name='list_post_user'),
    path('edit/<int:pk>', views.post_edit, name='edit'),
    path('delete/<int:pk>', views.post_delete, name='delete'),
    path('post/<int:pk>', views.post_details, name = 'details'),
]

microlly/accounts/models.py
from django.db import models

# Create your models here.

microlly/microlly_blog/models.py
from __future__ import unicode_literals
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Post(models.Model):
    title = models.CharField(max_length = 150)
    body = models.TextField()
    slug = models.SlugField()
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    release_date = models.DateTimeField(auto_now_add=True)
    edit_date = models.DateTimeField(auto_now=True)

    def preview(self):
        return self.body[0:25]+"..."

    def __str__(self):
        return self.title

    class Meta():
        verbose_name = 'Publication'
        verbose_name_plural = 'Publications'
        ordering =['-release_date']

microlly/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class SignUpForm(UserCreationForm):
    first_name = forms.CharField(
        max_length=30, required=False, help_text='Optional.')
    last_name = forms.CharField(
        max_length=30, required=False, help_text='Optional.')
    email = forms.EmailField(
        max_length=254, help_text='Required. Inform a valid email address.')

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name',
                  'email', 'password1', 'password2', )

microlly/microlly_blog/forms.py
from django import forms
from microlly_blog import models

class PostCreate(forms.ModelForm):
    class Meta:
        model = models.Post
        fields = ['title', 'body', 'slug']

class PostEdit(forms.ModelForm):
    class Meta:
        model = models.Post
        fields = ['title', 'body']

microlly/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout

# Create your views here.

def signup_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            #user = form.get_user()
            login(request, user)
            return redirect('microlly_blog:index')
    else:
        form = UserCreationForm()
    return render(request, 'accounts/signup.html', { 'form':form })

def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('microlly_blog:index')
    else:
        form = AuthenticationForm()
    return render(request, 'accounts/login.html', {'form':form})

def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return redirect('microlly_blog:index')

microlly/microlly_blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from microlly_blog.models import Post
from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied
from microlly_blog import forms
# Create your views here.

def index(request):
    posts = Post.objects.all()
    return render(request,'microlly_blog/index.html', {'latests_posts':posts})

def post_details (request, pk):
    post = get_object_or_404(Post, pk=pk)
    return render(request, 'microlly_blog/details.html', {'post':post})

@login_required(login_url = "/accounts/login/")
def post_create(request):
    if request.method == 'POST':
        form = forms.PostCreate(request.POST) 
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect('microlly_blog:index')
    else:
        form = forms.PostCreate()
    return render(request, 'microlly_blog/post_create.html', {'form':form})

@login_required(login_url = "/accounts/login/")
def post_edit(request, pk):
    post = get_object_or_404(Post, pk=pk)
    form = forms.PostEdit(request.POST or None, instance=post)
    if request.user != post.author:
        return redirect('microlly_blog:index')
    if request.method =='POST':
        if form.is_valid():
            post.save()
            return redirect('microlly_blog:index')
    context = {
        "form":form,
        "post":post,
    }
    return render(request, 'microlly_blog/details.html', context)

###Affichage des post liés à un utilisateur
#def post_user (request, author):
#   récupérer le user actuel <= en fait osef, on peut regarder les posts sans être co
#   ça favorisme le stalk
#   récuprer tous les posts avec filtre =>.filter()
#   dont le user est le créateur .object.all().filter(author=author)
#   retourner un template avec le dictionnaire de données contenant les posts
def list_post_user(request, author):
    if author:
        posts = Post.objects.filter(author=author)
        return render(request, 'microlly_blog/list_post_user.html', {'list_posts_user':posts})
    else:
        redirect('microlly_blog:index')

###Suppresion d'un post
#def post_delete(request, pk):
#   créer une instance du post à supprimer,
#   vérifier que le post.author == request.author sinon => return PermissionDenied
#   post.delete
#   rediriger vers l'index.

def post_delete (request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.user != post.author:
        redirect('microlly_blog:index')
    if request.method == 'POST':
        post.delete
        return redirect('microlly_blog:index')
    else:
        form = forms.PostEdit(request.POST or None, instance=post)
    return render(request, 'microlly_blog/index.html', {'form':form})

microlly/accounts/templates/accounts/login.html
{% extends 'base_layout.html' %}

{% block content %}
<h1>login.html</h1>
<form class="" action="{% url 'accounts:login' %}" method="POST">
    {% csrf_token %}
    {{ form }}
    {% if request.GET.next %}
        <input type="hidden" name="next" value="{{request.GET.next}}">
    {%endif%}
    <input type="submit" value="Login">
</form>
{% endblock %}

microlly/accounts/templates/accounts/signup.html
{% extends 'base_layout.html' %}

{% block content %}
<header>
    <h2>Latest post</h2>
</header>
<form class="" action="{% url 'accounts:signup' %}" method="POST">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Signup">
</form>
{% endblock %}

microlly/microlly_blog/templates/microlly_blog/details.html
{% extends 'base_layout.html' %}

{% block content %}
<h1>details.html</h1>
<h2>{{post.title}}</h2>
<p>{{ post.body }}</p>
<p>Created: {{ post.release_date }}</p>
<p>Edited: {{ post.edit_date }}</p>

<a href="{% url 'microlly_blog:edit' post.pk %}"> Editer le post</a>
<!--{% if form %}-->
<form class="" action="{% url 'microlly_blog:edit' post.pk %}" method="POST">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Edition">
</form>
<!--{%else%}
<form class="" action="{% url 'microlly_blog:edit' post.pk %}" method="POST">
    {% csrf_token %}
    <input type="submit" value="Edition">
</form>
{%endif%}-->
{% endblock %}

microlly/microlly_blog/templates/microlly_blog/index.html
{% extends 'base_layout.html' %}

{% block content %}
<section class="latest-post">
    <header>
        <h2>Latest post</h2>
    </header>
    {% if latests_posts %}
    {% for post in latests_posts %}
    <article>
        <h3><a href="{% url 'microlly_blog:details' post.pk %}">{{ post.title }}</a></h3>
        <p>Posted by <strong>{{post.author}}</strong> on {{post.release_date}}</p>
        <p>{{ post.preview }}</p>
        <a href="{% url 'microlly_blog:details' post.pk %}">Read more</a>
    </article>
    <hr>
    {% endfor %}
    {% else %}
    <p>Aucunes publications.</p>
    {% endif %}
</section>
{% endblock %}

microlly/microlly_blog/templates/microlly_blog/list_post_user.html
{% extends 'base_layout.html' %}

{% block content %}

{% if list_posts_user %}
{% for post in list_posts_user %}
<article>
    <h3>{{ post.title }}</h3>
    <p>Posted by <strong>{{post.author}}</strong> on {{post.release_date}}</p>
    <p>{{ post.preview }}</p>
    <a href="{% url 'microlly_blog:details' post.pk %}">Read more</a>
</article>
<hr>
{% endfor %}
{% else %}
<p>Aucunes publications.</p>
{% endif %}

{% endblock %}

microlly/microlly_blog/templates/microlly_blog/list_posts_user.html
{% extends 'base_layout.html' %}

{% block section-title %}
Post by: {{author}}
{% endblock %}

{% block content %}
<article class="row">
    {% for post in list_posts_user %}
    <div class="card-container col-md-6 col-lg-4">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">
                    <a class="badge badge-lightgreen" href="{% url 'microlly_blog:details' post.slug post.pk %}">
                        {{ post.title }}</a>
                </h4>
                <p class="card-text">
                    {{post.preview}}
                </p>
            </div>
            <div class="card-footer">
                <p class="card-text">
                    <small class="text-muted">
                        Posted by: <a href="{% url 'microlly_blog:list_post_user' post.author %}">{{post.author}}</a>
                        <span class="text-dark"></span>
                        on {{post.release_date}}
                    </small>
                </p>
                <p class="card-text">
                    <small class="text-muted">
                        Last update: {{post.edit_date}}
                    </small>
                </p>
            </div>
        </div>
    </div>
    {% endfor %}
</article>

<nav aria-label="Pagination author posts">
    <ul class="pagination justify-content-center">
        {% if list_posts_user.has_previous %}
        <li class="page-item"> <a class="page-link text-lightgreen" href="?page=1">&laquo; first</a> </li>
        <li class="page-item"><a class="page-link text-lightgreen" href="?page={{ list_posts_user.previous_page_number }}">previous</a></li>
        {% endif %}
        {% if list_posts_user.has_next %}
        <li class="page-item"><a class="page-link text-lightgreen" href="?page={{ list_posts_user.next_page_number }}">next</a></li>
        <li class="page-item"><a class="page-link text-lightgreen" href="?page={{ list_posts_user.paginator.num_pages }}">last &raquo;</a></li>
        {% endif %}
    </ul>
</nav>

{% endblock %}

microlly/microlly_blog/templates/microlly_blog/post_create.html
{% extends 'base_layout.html' %}

{% block content %}
    <h2>Create new post</h2> 
    <form class="" action="{% url 'microlly_blog:create' %}" method="POST">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Create">
    </form>
{% endblock %}

microlly/microlly_blog/templates/microlly_blog/post_edit.html
{% extends 'base_layout.html' %}

{% block content %}
    <h2>post_edit.html</h2> 
    <form class="" action="{% url 'microlly_blog:edit' post.pk %}" method="POST">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Edit">
    </form>
{% endblock %}

microlly/templates/base_layout.html
{% load static %}

<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link rel="stylesheet" type="text/css" media="screen" href="{% static 'css/style.css' %}" />
    <title>Eheheh</title>
</head>

<body>
    <div class="contenu">
        <header class="banner rounded-corners-banner">
            <h1>Microlly</h1>
            <h2>A microbbloging app</h2>
            <nav>
                <ul>
                    <li>
                        <form class="" action="{% url 'microlly_blog:index' %}" method="POST">
                            {% csrf_token %}
                            <button class="nav-button" type="submit">HOME</button>
                        </form>
                    </li>
                    <li>
                        <form class="" action="{% url 'microlly_blog:create' %}" method="POST">
                            {% csrf_token %}
                            <button class="nav-button" type="submit">CREATE</button>
                        </form>
                    </li>
                    <li>
                        <form class="" action="{% url 'accounts:logout' %}" method="POST">
                            {% csrf_token %}
                            <button class="nav-button" type="submit">LOG OUT</button>
                        </form>
                    </li>
                    <li>
                        <form class="" action="{% url 'accounts:login' %}" method="POST">
                            {% csrf_token %}
                            <button class="nav-button" type="submit">LOG IN</button>
                        </form>
                    </li>
                    <li>
                        <form class="" action="{% url 'accounts:signup' %}" method="POST">
                            {% csrf_token %}
                            <button class="nav-button" type="submit">SIGN UP</button>
                        </form>
                    </li>
                </ul>
            </nav>
        </header>
        {% block content %}
        {% endblock %}
        <footer class="footer rounded-corners-footer">
            <p>Microblog crée par <b>Remy LEFEVRE </b> et <b>Sergen KOVAR</b>, 2018</p>
        </footer>
    </div>
</body>

</html>

microlly/templates/form.html
{% load widget_tweaks %}

{% for hidden_field in form.hidden_fields %}
{{ hidden_field }}
{% endfor %}

{% if form.non_field_errors %}
<div class="alert alert-danger" role="alert">
    {% for error in form.non_field_errors %}
    {{ error }}
    {% endfor %}
</div>
{% endif %}

{% for field in form.visible_fields %}
<div class="form-group">
    {{ field.label_tag }}
    {% if form.is_bound %}
        {% if field.errors %}
            {% render_field field class="form-control is-invalid" %}
            {% for error in field.errors %}
                <div class="invalid-feedback">
                    {{ error }}
                </div>
            {% endfor %}
        {% else %}
            {% render_field field class="form-control is-valid" %}
        {% endif %}
    {% else %}
        {% render_field field class="form-control" %}
    {% endif %}
    {% if field.help_text %}
    <small class="form-text text-muted">{{ field.help_text }}</small>
    {% endif %}
</div>
{% endfor %}